---
- defaults:
    link:
      create: true
      relink: true

- shell:
    - ["git submodule update --init --recursive", "Installing submodules"]

- clean: ['~', '~/.config']

- create:
    - ~/.tmux/plugins
    - ~/.config/yamlfmt
    - ~/.config/custom
    - ~/Documents
    - ~/GIT

- create:
    ~/.ssh:
      mode: 0700

#- shell:
#    - command: git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf; ~/.fzf/install
#      description: "install fzf"
#      stdin: true

#- link:
#    ~/.config/ghostty: terminals/ghostty

- link:
    ~/.tmux.conf: terminals/tmux.conf
    ~/.tmux/plugins/tpm: terminals/tpm
    ~/.config/nvim: editors/nvim
    ~/.config/yamlfmt/.yamlfmt: tools/yamlfmt
    ~/.aliases: tools/aliases
    ~/.gitconfig: tools/git/gitconfig
    ~/.config/qt5ct: gui/qt5ct
    ~/.config/gtk-3.0: gui/gtk-3
    ~/.local/share/icons/candy-icons: gui/candy-icons
