---
- defaults:
    link:
      create: true
      relink: true

- shell:
    - ["git submodule update --init --recursive", "Installing submodules"]

- clean: ['~', '~/.config']

- create:
    - ~/.tmux/plugins
    - ~/.config/yamlfmt
    - ~/Documents
    - ~/GIT

- create:
    ~/.ssh:
      mode: 0700
