font_family      Victor Mono
bold_font        Victor Mono Bold
bold_italic_font Victor Mono Bold Italic
font_size 10.0
scrollback_lines 50000
enable_audio_bell no
background_opacity 0.6
background_blur 0
command = tmux attach -t init || tmux new -s init
